### ISSUE TITLE
Seems not to support https?

### ISSUE THREAD

**Issue by agenge** [int32bit/python-harborclient#2]
hi! 
    I found that this client does not support https. Are there plans to support https?

**Comment by int32bit** [comment]
I don't really test this, but I think it should support https, could you provide your error log?

**Comment by agenge** [comment]
```
docker run  -e HARBOR_USERNAME="admin" \
   -e HARBOR_PASSWORD="xxxx" \
   -e HARBOR_URL="http://192.168.x.x" \
   --net host --rm krystism/harborclient user-list
ERROR (SSLError): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)```

**Comment by theemptyone** [comment]
I'm running into the same issue.  

I'm able to pull from repositories on the harbor, but the api calls are failing for SSL.

**Comment by moooofly** [comment]
I'm running into the same issue.

error log as follow:

```
[#4#root@ubuntu-1604 ~/workspace/SandBox/harborclient]$harbor --os-baseurl https://localhost login --username admin --password Harbor12345
ERROR (SSLError): HTTPSConnectionPool(host='localhost', port=443): Max retries exceeded with url: /login (Caused by SSLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)'),))
[#5#root@ubuntu-1604 ~/workspace/SandBox/harborclient]$harbor --os-baseurl http://localhost login --username admin --password Harbor12345
ERROR (SSLError): HTTPSConnectionPool(host='localhost', port=443): Max retries exceeded with url: /login (Caused by SSLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)'),))
[#6#root@ubuntu-1604 ~/workspace/SandBox/harborclient]$
```

another test by `curl` as follow:

```
[#108#root@ubuntu-1604 ~/workspace/SandBox/harborclient]$curl -X GET --header 'Accept: application/json' 'https://11.11.11.12/api/repositories?project_id=2&q=prj&page=1&page_size=10' -i -u admin:Harbor12345
curl: (60) server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
[#109#root@ubuntu-1604 ~/workspace/SandBox/harborclient]$

[#109#root@ubuntu-1604 ~/workspace/SandBox/harborclient]$curl -X GET --header 'Accept: application/json' 'https://11.11.11.12/api/repositories?project_id=2&q=prj&page=1&page_size=10' -k -i -u admin:Harbor12345
HTTP/1.1 200 OK
Server: nginx/1.11.13
Date: Wed, 25 Oct 2017 03:57:11 GMT
Content-Type: application/json; charset=utf-8
Content-Length: 250
Connection: keep-alive
Set-Cookie: beegosessionID=093d256d45165448c104adda65079238; Path=/; secure; HttpOnly
X-Total-Count: 1

[
  {
    "id": 1,
    "name": "prj1/hello-world",
    "project_id": 2,
    "description": "",
    "pull_count": 0,
    "star_count": 0,
    "tags_count": 3,
    "creation_time": "2017-10-24T06:37:54Z",
    "update_time": "2017-10-24T06:37:54Z"
  }
][#110#root@ubuntu-1604 ~/workspace/SandBox/harborclient]$
```

with `-k` option, I can get the right results by `curl` command.

So I think, `python-harborclient` need a feature like that.

**Comment by moooofly** [comment]
Has there been any progress on this issue?

**Comment by int32bit** [comment]
Yes, current version don't support https, but I guess it's easy to add this feature, if it doesn't matter to check cert, we can just add `verify=False` to requests call[1].

1. https://github.com/int32bit/python-harborclient/blob/master/harborclient/client.py#L177.

**Comment by int32bit** [comment]
I added '--insecure' option to harborclient that allowed connections to SSL sites without certs(like curl -k), but I'm really not free to test if it works well now.

```
harbor --insecure list
```

**Comment by moooofly** [comment]
not working.

```
[#104#root@ubuntu-1604 ~/workspace/SandBox/harborclient]$harbor --os-baseurl http://localhost --insecure login --username admin --password Harbor12345
Traceback (most recent call last):
  File "/usr/local/bin/harbor", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/harborclient/shell.py", line 390, in main
    HarborShell().main(argv)
  File "/usr/local/lib/python2.7/dist-packages/harborclient/shell.py", line 315, in main
    self.cs.authenticate()
  File "/usr/local/lib/python2.7/dist-packages/harborclient/v2/client.py", line 72, in authenticate
    self.client.authenticate()
  File "/usr/local/lib/python2.7/dist-packages/harborclient/client.py", line 277, in authenticate
    'password': self.password})
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 640, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 218, in resolve_redirects
    **adapter_kwargs
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 506, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='localhost', port=443): Max retries exceeded with url: /login (Caused by SSLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)'),))
[#105#root@ubuntu-1604 ~/workspace/SandBox/harborclient]$
```

**Comment by int32bit** [comment]
Please pull the code again :)

**Comment by moooofly** [comment]
After a fresh pull, it's still not working,

```
[#127#root@ubuntu-1604 ~/workspace/SandBox/harborclient]$harbor login
usage: harbor login --username <username> --password <password>
error: argument --username is required
Try 'harbor help login' for more information.
[#128#root@ubuntu-1604 ~/workspace/SandBox/harborclient]$
[#128#root@ubuntu-1604 ~/workspace/SandBox/harborclient]$
[#128#root@ubuntu-1604 ~/workspace/SandBox/harborclient]$harbor login --username admin --password Harbor12345
ERROR (CommandError): You must provide harbor url via either --os-baseurl or env[HARBOR_URL].
[#129#root@ubuntu-1604 ~/workspace/SandBox/harborclient]$
[#129#root@ubuntu-1604 ~/workspace/SandBox/harborclient]$harbor --os-baseurl http://localhost login --username admin --password Harbor12345
ERROR (CommandError): You must provide username via either --os-username or env[HARBOR_USERNAME].
[#130#root@ubuntu-1604 ~/workspace/SandBox/harborclient]$
[#130#root@ubuntu-1604 ~/workspace/SandBox/harborclient]$harbor --os-baseurl http://localhost --os-username admin  login --username admin --password Harbor12345
ERROR (CommandError): You must provide project via either --os-project or env[HARBOR_PROJECT].
[#131#root@ubuntu-1604 ~/workspace/SandBox/harborclient]$
[#131#root@ubuntu-1604 ~/workspace/SandBox/harborclient]$
[#131#root@ubuntu-1604 ~/workspace/SandBox/harborclient]$harbor --os-baseurl http://localhost --os-username admin --os-project 3 login --username admin --password Harbor12345
password: Traceback (most recent call last):
  File "/usr/local/bin/harbor", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/harborclient/shell.py", line 407, in main
    print(_("... terminating harbor client"), file=sys.stderr)
NameError: global name '_' is not defined
[#132#root@ubuntu-1604 ~/workspace/SandBox/harborclient]$
[#132#root@ubuntu-1604 ~/workspace/SandBox/harborclient]$
[#132#root@ubuntu-1604 ~/workspace/SandBox/harborclient]$harbor --os-baseurl http://localhost --os-username admin --os-password Harbor12345 --os-project 3 login --username admin --password Harbor12345
Traceback (most recent call last):
  File "/usr/local/bin/harbor", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/harborclient/shell.py", line 405, in main
    HarborShell().main(argv)
  File "/usr/local/lib/python2.7/dist-packages/harborclient/shell.py", line 330, in main
    self.cs.authenticate()
  File "/usr/local/lib/python2.7/dist-packages/harborclient/v2/client.py", line 83, in authenticate
    self.client.authenticate()
  File "/usr/local/lib/python2.7/dist-packages/harborclient/client.py", line 267, in authenticate
    verify=self.verify_cert)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 640, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 218, in resolve_redirects
    **adapter_kwargs
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 506, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='localhost', port=443): Max retries exceeded with url: /login (Caused by SSLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)'),))
[#133#root@ubuntu-1604 ~/workspace/SandBox/harborclient]$
```

I almost lose my patience, I just want to `login`~~~

**Comment by int32bit** [comment]
As I saw, your `baseurl` is `http` rather than `https`. In addition, I guess you missed `--insecure` option in your command.

**Comment by int32bit** [comment]
I suggest you use following script to test your environment:

```bash
cat >harborrc <<EOF
export HARBOR_USERNAME=admin
export HARBOR_PASSWORD=Harbor12345
export HARBOR_URL=https://localhost
export HARBOR_PROJECT=1
EOF
source harborrc
harbor --insecure login --username admin --password Harbor12345
harbor --insecure list
```

**Comment by moooofly** [comment]
```
[#149#root@ubuntu-1604 ~/workspace/SandBox/harborclient]$git pull
Already up-to-date.
[#150#root@ubuntu-1604 ~/workspace/SandBox/harborclient]$
[#150#root@ubuntu-1604 ~/workspace/SandBox/harborclient]$cat >harborrc <<EOF
> export HARBOR_USERNAME=admin
> export HARBOR_PASSWORD=Harbor12345
> export HARBOR_URL=https://localhost
> export HARBOR_PROJECT=1
> EOF
[#151#root@ubuntu-1604 ~/workspace/SandBox/harborclient]$source harborrc
[#152#root@ubuntu-1604 ~/workspace/SandBox/harborclient]$
[#152#root@ubuntu-1604 ~/workspace/SandBox/harborclient]$echo $HARBOR_USERNAME
admin
[#153#root@ubuntu-1604 ~/workspace/SandBox/harborclient]$echo $HARBOR_PASSWORD
Harbor12345
[#154#root@ubuntu-1604 ~/workspace/SandBox/harborclient]$echo $HARBOR_URL
https://localhost
[#155#root@ubuntu-1604 ~/workspace/SandBox/harborclient]$echo $HARBOR_PROJECT
1
[#156#root@ubuntu-1604 ~/workspace/SandBox/harborclient]$
[#156#root@ubuntu-1604 ~/workspace/SandBox/harborclient]$harbor --insecure login --username admin --password Harbor12345
/usr/local/lib/python2.7/dist-packages/urllib3/connectionpool.py:858: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
Traceback (most recent call last):
  File "/usr/local/bin/harbor", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/harborclient/shell.py", line 405, in main
    HarborShell().main(argv)
  File "/usr/local/lib/python2.7/dist-packages/harborclient/shell.py", line 336, in main
    args.func(self.cs, args)
  File "/usr/local/lib/python2.7/dist-packages/harborclient/v2/shell.py", line 33, in do_login
    resp = cs.users.login(args.username, args.password, cs.baseurl)
  File "/usr/local/lib/python2.7/dist-packages/harborclient/v2/users.py", line 64, in login
    resp = requests.post(baseurl + "/login", data)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 506, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='localhost', port=443): Max retries exceeded with url: /login (Caused by SSLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)'),))
[#157#root@ubuntu-1604 ~/workspace/SandBox/harborclient]$
[#157#root@ubuntu-1604 ~/workspace/SandBox/harborclient]$
[#157#root@ubuntu-1604 ~/workspace/SandBox/harborclient]$harbor --insecure list
/usr/local/lib/python2.7/dist-packages/urllib3/connectionpool.py:858: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
/usr/local/lib/python2.7/dist-packages/urllib3/connectionpool.py:858: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
+------+------------+------+------------+------------+------------+-------------+
| name | project_id | size | tags_count | star_count | pull_count | update_time |
+------+------------+------+------------+------------+------------+-------------+
+------+------------+------+------------+------------+------------+-------------+
[#158#root@ubuntu-1604 ~/workspace/SandBox/harborclient]$
```

is it right?

**Comment by int32bit** [comment]
As I see, it works now.  But you can also download latest code to suppress `InsecureRequestWarning` :)

```
$ harbor --insecure login --username admin --password Harbor12345
Successfully login, session id: 8e2db3d161bb5996ceddde49a0f22c31
```
