### ISSUE TITLE
ERROR (AttributeError): 'module' object has no attribute 'update_headers' got when command executed

### ISSUE THREAD

**Issue by Lazast** [int32bit/python-harborclient#4]
Follows are the debug info:
DEBUG (connectionpool:208) Starting new HTTP connection (1): abchub.abc.com
DEBUG (connectionpool:396) http://abchub.abc.com:80 "POST /login HTTP/1.1" 200 0
DEBUG (client:270) Successfully login, session id: 07f08c213887fb80fbe692d644fc48ac
DEBUG (shell:367) 'module' object has no attribute 'update_headers'
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/harborclient/shell.py", line 365, in main
    HarborShell().main(argv)
  File "/usr/lib/python2.7/site-packages/harborclient/shell.py", line 296, in main
    args.func(self.cs, args)
  File "/usr/lib/python2.7/site-packages/harborclient/v2/shell.py", line 43, in do_user_list
    _, users = cs.users.list()
  File "/usr/lib/python2.7/site-packages/harborclient/v2/users.py", line 28, in list
    return self._list("/users")
  File "/usr/lib/python2.7/site-packages/harborclient/base.py", line 28, in _list
    resp, body = self.api.client.get(url)
  File "/usr/lib/python2.7/site-packages/harborclient/client.py", line 236, in get
    return self._cs_request(url, 'GET', **kwargs)
  File "/usr/lib/python2.7/site-packages/harborclient/client.py", line 221, in _cs_request
    **kwargs)
  File "/usr/lib/python2.7/site-packages/harborclient/client.py", line 207, in _time_request
    resp, body = self.request(url, method, **kwargs)
  File "/usr/lib/python2.7/site-packages/harborclient/client.py", line 171, in request
    api_versions.update_headers(kwargs["headers"], self.api_version)
AttributeError: 'module' object has no attribute 'update_headers'
ERROR (AttributeError): 'module' object has no attribute 'update_headers'

**Comment by int32bit** [comment]
Please upgrade to latest version(rebuild image) and try again.
